### PR TITLE
dependencies bump, sphinx-panel formatting (jupyterbook 0.13)

### LINKED ISSUE #99: Update cookiecutter to 2.0
https://github.com/cookiecutter/cookiecutter/releases . Might be some new feature to take advantage of...

### PR DESCRIPTION
**Pull request by scottyhq**
closes #99 and #103

### CODE REVIEW

**Comment by jomey** [comment]
Should we try in this PR to have the 'Build and test on OS' pass here?

I can hold off on PR #113 until this is done. Would be nice to have working GH actions again.

**Comment by scottyhq** [comment]
> Should we try in this PR to have the 'Build and test on OS' pass here? 

I'm not sure why it wasn't running before. Either the entire workflow was disabled b/c of the 'schedule' trigger. Or renaming test.yml -> build_website.yaml confused the branch protection...
image

**Comment by scottyhq** [comment]
@jomey i think this is ready to go, i'm fine either way merging this first or #113

**Review by jomey — APPROVED** [review]

**Comment by jomey** [comment]
> @jomey i think this is ready to go, i'm fine either way merging this first or #113

This looks ready to go. Let's merge ...

**Pull request merged**
